### ISSUE TITLE
[Feature] Support work in SSR

### ISSUE THREAD

**Issue by nonzzz** [fect-org/fect#138]
# Feature request 🚀

### Expected:

- [ ] All component can work with SSR.
- [ ] Use new style System . 

### Others:

May it support before 1.5.0 .

**Comment by XeryYue** [comment]
If you found some component can not work with ssr,Please contact me,Thanks

**Comment by abigmiu** [comment]
我在使用nuxt3 引入 fectui时遇到了点问题。 网上搜不到资料。 所以不得以在issue提问。

**Comment by abigmiu** [comment]
我在使用nuxt3 引入 fectui时遇到了点问题。 网上搜不到资料。 所以不得以在issue提问。

图片是我配置fectui 的步骤。 但是不起作用。 请问是我哪里有问题


![wecom-temp-45624cf541bcd8a605603427d1f04679](https://user-images.githubusercontent.com/43983920/174935818-5c33db3e-2fa8-41ff-941f-e2a19610f561.png)
![wecom-temp-a7b5b20fbe21290007aac1eb17322993](https://user-images.githubusercontent.com/43983920/174935832-74d20be6-81f7-4b0f-a865-064bdb2d1ab9.png)
![wecom-temp-6040ace23d0cdb0c0be3fc1ca34f6f18](https://user-images.githubusercontent.com/43983920/174935841-c5a98659-affc-4f1e-b63d-6a2dd8b1f500.png)

**Comment by nonzzz** [comment]
@abigmiu 文档由于最近在重构,SSR的引入方式并没有被更新。这里我会更新一个quick start.以及同步现有文档的方式。

**Comment by nonzzz** [comment]
@abigmiu  [nuxt-demo](https://github.com/fect-org/example/tree/master/nuxt-getting-stared) 可以看一下nuxt的example。由于`vite-plugin-style-import`做了`breakChange`但是未按照`semver`进行升级你可以参照这个如果还有遇到问题可以联系我。

**Comment by abigmiu** [comment]
> 

可以运行了， 谢谢你

**Comment by abigmiu** [comment]
> @abigmiu [nuxt-demo](https://github.com/fect-org/example/tree/master/nuxt-getting-stared) 可以看一下nuxt的example。由于`vite-plugin-style-import`做了`breakChange`但是未按照`semver`进行升级你可以参照这个如果还有遇到问题可以联系我。

可以运行了， 谢谢你
