### ISSUE TITLE
github desktop error

### ISSUE THREAD

**Issue by qiang001** [fect-org/fect#157]
# Bug report 🐞

## Actual results (or Errors)
![QQ图片20211216141205](https://user-images.githubusercontent.com/35440329/146317962-126f4771-394c-49d5-9789-7345507ddac3.png)

**Comment by XeryYue** [comment]
@qiang001  I already remove husky . You can  pull the latest code to try  it.    :  )

**Comment by qiang001** [comment]
works fine now. good
