### ISSUE TITLE
[Bug]fe-grid 同时设置三个断点，最后一个不生效

### ISSUE THREAD

**Issue by QiYuOr2** [fect-org/fect#171]
# Bug report 🐞

https://codesandbox.io/s/flamboyant-cache-wz5n8?file=/src/App.vue

## Version & Environment

- `vue@3.0.0`
- `@fect-ui/vue@1.1.0`

## Expection

`{ min: '900px', max: '1280px' }` 时，宽度为6

## Actual results (or Errors)

`{ min: '900px', max: '1280px' }`时，宽度仍为12

**Comment by XeryYue** [comment]
@QiYuOr2  Thanks for your attention. I have seen the case. Really have  problem. I will fix it after soon. And release it in v1.2.0.

**Comment by XeryYue** [comment]
@QiYuOr2  我fix了这个问题。这个bug会随着这周的`feature`版本一起发布。你可以先这么定义。然后升级版本达到你想要效果。
