### ISSUE TITLE
Modal didn't achieve the expected effect 

### ISSUE THREAD

**Issue by HinokiSu** [fect-org/fect#174]
# Bug report 🐞

## Version & Environment
```
"@fect-ui/vue": "^1.1.1",
```
- Browser: `Microsoft Edge`  version 97.0.1072.62 (64)
## Expection

- When the interval is 1s, click the blank again, the modal box will no longer appear 

## Actual results (or Errors)
> The recorded gif is a bit faster than the actual display 

![click-modal](https://user-images.githubusercontent.com/93910087/149649560-418fc626-fa1f-455a-b290-1a99e67d7fff.gif)

![click-func-call-modal](https://user-images.githubusercontent.com/93910087/149649569-606b236c-3d56-47b7-91cb-8fdf0c1bb30d.gif)

**Comment by XeryYue** [comment]
Thanks for your feedback. I will check the cause

**Comment by XeryYue** [comment]
I found reason, I'll fix bug in next version. Thanks

**Comment by XeryYue** [comment]
fix it at this commit https://github.com/fect-org/fect/commit/0a1e7d2dbaa62af9f365b53a4084a22c1e7a817d 
next version will release in next Friday.
