### ISSUE TITLE
Stacking issue when using multiple select in modal

### ISSUE THREAD

**Issue by HinokiSu** [fect-org/fect#176]
# About `styles` 🛠️
Stacking issue when using multiple select in modal 

- env: `    "@fect-ui/vue": "1.2.1"`
- browser: `Microsoft Edge  97`

## Demo
https://codesandbox.io/s/fect-ui--multi-select-modal-lm9de?file=/src/App.vue
## Show

![multi-select-modal](https://user-images.githubusercontent.com/93910087/150748257-80600df3-cc36-4724-836b-a4a4d8de9248.gif)

**Comment by XeryYue** [comment]
It seems to be caused by the z-index

**Comment by XeryYue** [comment]
If you are using this func . can increase   class `.fect-select__dropdown`  css variable `z-index` level. And I will check all components related to `z-index` , will fix in v1.2.2 in this week.

**Comment by XeryYue** [comment]
It already fixed. I will release it as soon.
