### ISSUE TITLE
[Bug] radio组件的value初始化值为字符串时报错

### ISSUE THREAD

**Issue by QiYuOr2** [fect-org/fect#192]
# Bug report 🐞

## Version & Environment
`@fect-ui/vue@1.3.4`

## Actual results (or Errors)
![F1621DF6798E3A9B9581BFE957230CA6](https://user-images.githubusercontent.com/48339849/156715455-3a928132-abde-4db2-b5f7-7d4fb5688523.jpg)
![4262375D5580545C85DECB058643920A](https://user-images.githubusercontent.com/48339849/156715495-26f62342-6f5f-46e5-9e35-783723ce3fba.jpg)
![E3E78937D715D24D21A51A6965E576A7](https://user-images.githubusercontent.com/48339849/156715520-3f128448-1568-4403-b7f5-7565b51ee039.jpg)

**Comment by XeryYue** [comment]
这个PR将会修复这个问题。并且会在今天的`1.3.5`进行bug修复
