### ISSUE TITLE
输入框的密码样式出现两个隐藏密码按钮

### ISSUE THREAD

**Issue by HinokiSu** [fect-org/fect#194]
# Bug report 🐞
当输入框为空时，输入内容，会出现两个隐藏/显示密码按钮
![fect-ui_input--password](https://user-images.githubusercontent.com/93910087/156724718-1858557a-73d8-4299-bdbf-3963856264d7.jpg)

## Version & Environment
`"@fect-ui/vue": "1.3.6"`

**Comment by XeryYue** [comment]
可以提供一个最小的复现demo吗 @HinokiSu

**Comment by XeryYue** [comment]
> https://codesandbox.io/s/fect-ui--test-demo-ktm1es?file=/src/App.vue ![fect-ui_input__password](https://user-images.githubusercontent.com/93910087/156726583-4910603f-13cd-49b7-b554-57ea621650c7.gif)

看起来有问题。但是在复现的demo上我没有找到代码。

**Comment by HinokiSu** [comment]
> > https://codesandbox.io/s/fect-ui--test-demo-ktm1es?file=/src/App.vue ![fect-ui_input__password](https://user-images.githubusercontent.com/93910087/156726583-4910603f-13cd-49b7-b554-57ea621650c7.gif)
> 
> 看起来有问题。但是在复现的demo上我没有找到代码。

```vue
<template>
  <div>
    <fe-input
      placeholder="请输入"
      v-model="value"
      type="password"
    />
  </div>
</template>

<script>
import { ref } from "vue";
export default {
  name: "App",
  setup() {
    const value = ref("");

    return {
      value,
    };
  },
};
</script>

<style>
</style>

```

**Comment by HinokiSu** [comment]
好像只有 Edge浏览器有这个问题  ：(

**Comment by XeryYue** [comment]
@HinokiSu  能提供下 edge的版本吗。我会在这次修复掉safari 和edge的问题。

**Comment by HinokiSu** [comment]
`Microsoft Edge
版本 98.0.1108.62 (官方内部版本) (64 位)
`

**Comment by XeryYue** [comment]
这个issue会修复在edge下的问题。如果在下次release后依然存在 这个issue可以重新打开。
