### ISSUE TITLE
模态框中使用多选框，无法正常使用

### ISSUE THREAD

**Issue by HinokiSu** [fect-org/fect#198]
# Bug report 🐞
下拉框无法正常显示
Demo: https://codesandbox.io/s/fect-ui--multi-select-t8wb0y  

## Version & Environment
`"@fect-ui/vue": "1.3.6"`
`"vue": "^3.2.25"`
`Chrome 版本 98.0.4758.102（正式版本） （64 位）`
## Actual results (or Errors)
![image](https://user-images.githubusercontent.com/93910087/156916151-7272d5f5-e66c-4639-abef-fccc6e455b37.png)

**Comment by XeryYue** [comment]
感谢。这个问题会进行修复

**Comment by XeryYue** [comment]
![image](https://user-images.githubusercontent.com/52351095/156920889-a6c9626d-7a70-48b6-9e79-1fef09ba640c.png)
已经修复。 Bug原因是因为是在onMounted阶段获取的`width`和`height`。 因为modal 组件一开始是un visible的所以当select运行的时候。并没有设置上。这里做了个优化修复。感谢提供bug定位。
