### ISSUE TITLE
[Bug] 卡片组件部分样式缺失

### ISSUE THREAD

**Issue by QiYuOr2** [fect-org/fect#205]
# Bug report 🐞

https://codesandbox.io/s/recursing-franklin-k6mzly?file=/src/App.vue

## Version & Environment

- `@fect-ui/vue@1.4.0-rc.0`

## Actual results (or Errors)

卡片的边框和边距样式缺失，开发者工具调试未找到对应的css变量

**Comment by QiYuOr2** [comment]
除了卡片外的其他组件也有不同程度的样式缺失

**Comment by XeryYue** [comment]
详情参阅:https://github.com/fect-org/fect/releases/tag/v1.3.7
