### ISSUE TITLE
Add  deployment snapshot for pr.

### ISSUE THREAD

**Issue by nonzzz** [fect-org/fect#208]
# Feature request 🚀

### Expected:

Add a deployment snapshot to view the `ux` effect every time you pr

**Comment by zaunist** [comment]
How about we choose netlify for deployment?

**Comment by nonzzz** [comment]
I think we can deploy the website rc and prod with netlify. I'd be happy if you want add snapshot

**Comment by nonzzz** [comment]
@zaunist  Thanks :)
