### ISSUE TITLE
[Bug] fe-tabs无法通过直接改变active的value来切换tab

### ISSUE THREAD

**Issue by QiYuOr2** [fect-org/fect#225]
# Bug report 🐞

## Version & Environment

- `@fect-ui/vue@1.5.0-rc.1`
- `vue@3.2.33`

## Expection

手动修改active绑定的变量可以切换tab

## Actual results (or Errors)

https://stackblitz.com/edit/vue-lcup1k?file=src/App.vue

**Comment by XeryYue** [comment]
他看起来像是一个bug。根据源码的定义。[tabs](https://github.com/fect-org/fect/blob/master/packages/vue/src/tabs/tabs.tsx) 确实是没法切换。这个bug会在下个版本进行修复。

**Comment by XeryYue** [comment]
这个bug已经fix掉了 #https://github.com/fect-org/fect/commit/3d8c9863e8a8dd9b2e8bf08f5ee62d0c4656526a
