### ISSUE TITLE
Can we change the `dark mode` color scheme of the website?

### ISSUE THREAD

**Issue by zaunist** [fect-org/fect#228]
# About `styles` 🛠️
![image](https://user-images.githubusercontent.com/38528079/167895920-358073fd-b7ba-473d-910f-40d330b115c9.png)

When switching to dark mode, the strong contrast between black and white makes it hard on the eyes, perhaps it would be better to switch to a more muted color scheme.

Like this:

![image](https://user-images.githubusercontent.com/38528079/167896298-8feb98d7-3176-4549-82b5-f6b04d6340a8.png)

Of course, if this issue is accepted, I will be happy to change it.

**Comment by nonzzz** [comment]
Maybe you need to refer to vercel's design system. This project style is base on `vercel` design system. 
But for future. The dark mod will be change. Currently, `fect` is in `ver1.x` and in my mind. change the base design isn't a wise move. although vue docs dark mod is soft. we also provide `css variable` can change the base theme. I think is user behavior. So. change the base theme system for current ver 
i think can be later. After ver `2.x` : )


May the `1.x` i plan to add some component and break to `2.x`. If in `2.x` this issue can be reoepn. Thanks. @zaunist

**Comment by zaunist** [comment]
Got it, close.
